### ISSUE TITLE
Missing datasets

### ISSUE THREAD

**Issue by ngarneau** [GaryYufei/ACL2021MF#1]
Hi,

The dataset folder is missing a couple of dataset, I think.
When I try to run
```
python train_T5.py --config t5_base.yml --config-override do_pretrain_lm_init False freeze_param False --serialization-dir dataset/commonGen_transL3_mf --train
```
I get the following error
```
FileNotFoundError: [Errno 2] No such file or directory: 'dataset/commongen.train.jsonl'
```
Thanks for your help!
Nicolas

**Comment by GaryYufei** [comment]
I have updated a link to download the commonsense generation and e2e tasks in README.

Please let me know if there are other issues.
